export const ACTIONS_DYNAMIC = {
  CALL_PARENT: 'CALL_PARENT',
  CALL_CHILD: 'CALL_CHILD',
};

export const MUTATIONS_DYNAMIC = {
  SET_PARENT_COUNT: 'SET_PARENT_COUNT',
  SET_CHILD_COUNT: 'SET_CHILD_COUNT',
};

export const ACTIONS_STATIC = {
  CALL_PARENT: 'CALL_PARENT',
  CALL_CHILD: 'CALL_CHILD',
};
export const MUTATIONS_STATIC = {
  SET_PARENT_COUNT: 'SET_PARENT_COUNT',
  SET_CHILD_COUNT: 'SET_CHILD_COUNT',
};
